version: 2
jobs:
  build:

    working_directory: ~/app
    docker:
      - image: laurentmorissette/lms-chuck-norris-jokes:latest
    steps:
      - checkout
      - restore_cache:
          key: pet-clinic-{{checksum "pom.xml"}}
      - run: echo "Test"