version: 2
jobs:
  build:

    working_directory: ~/app
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      = run:
        - echo DIR IS
        - pwd
        #- restore_cache:
        #   key: app-{{checksum "pom.xml"}}
      - run: echo "Test"
          #- run: mvn dependency:go-offline # gets the project dependencies
          #- save_cache:
          #   paths:
          #     ~/.m2
          #  key: app-{{checksum "pom.xml"}}

          #- run: mvn package
          #- store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
        # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          #   path: target/surefire-reports

          #- store_artifacts: # store the uberjar as an artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
        #   path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
        # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
